apiVersion: g8s.github.com/v1alpha1
kind: SSHKey
metadata:
  labels:
    app.kubernetes.io/name: sshkey
    app.kubernetes.io/instance: sshkey-sample
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kb
  name: sshkey-sample
spec:
  # TODO(user): Add fields here
