apiVersion: g8s.github.com/v1alpha1
kind: PGPKey
metadata:
  labels:
    app.kubernetes.io/name: pgpkey
    app.kubernetes.io/instance: pgpkey-sample
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kb
  name: pgpkey-sample
spec:
  # TODO(user): Add fields here
