apiVersion: g8s.github.com/v1alpha1
kind: TLSCert
metadata:
  labels:
    app.kubernetes.io/name: tlscert
    app.kubernetes.io/instance: tlscert-sample
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kb
  name: tlscert-sample
spec:
  # TODO(user): Add fields here
