# permissions for end users to edit pgpkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pgpkey-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kb
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
  name: pgpkey-editor-role
rules:
- apiGroups:
  - g8s.github.com
  resources:
  - pgpkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - g8s.github.com
  resources:
  - pgpkeys/status
  verbs:
  - get
