# permissions for end users to edit tlscerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tlscert-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kb
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
  name: tlscert-editor-role
rules:
- apiGroups:
  - g8s.github.com
  resources:
  - tlscerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - g8s.github.com
  resources:
  - tlscerts/status
  verbs:
  - get
